######################################################################
# Automatically generated by qmake (3.0) ?? ???. 31 22:26:27 2014
######################################################################

TEMPLATE = app
TARGET = gis_mode_gui
INCLUDEPATH += ../../src/

# Input
SOURCES += gis_mode_gui.cpp ../../src/qltgplogger.cpp
