######################################################################
# Automatically generated by qmake (3.0) ?? ???. 31 22:23:19 2014
######################################################################

TEMPLATE = app
TARGET = two_axes_gui
INCLUDEPATH += ../../src/

# Input
SOURCES += two_axes_gui.cpp ../../src/qltgplogger.cpp
