######################################################################
# Automatically generated by qmake (3.0) ?? ???. 31 22:24:33 2014
######################################################################

TEMPLATE = app
TARGET = gis_mode_img
INCLUDEPATH += ../../src/

# Input
SOURCES += gis_mode_img.cpp ../../src/qltgplogger.cpp
