######################################################################
# Automatically generated by qmake (3.0) ?? ???. 31 22:20:20 2014
######################################################################

TEMPLATE = app
TARGET = general_mode_img
INCLUDEPATH += ../../src/

# Input
SOURCES += general_mode_img.cpp ../../src/qltgplogger.cpp
