######################################################################
# Automatically generated by qmake (3.0) ?? ???. 31 22:23:19 2014
######################################################################

TEMPLATE = app
TARGET = general_mode_gui
INCLUDEPATH += ../../src/

# Input
SOURCES += general_mode_gui.cpp ../../src/qltgplogger.cpp
