######################################################################
# Automatically generated by qmake (3.0) ?? ???. 24 14:34:01 2017
######################################################################

TEMPLATE = app
TARGET = qltdebug
INCLUDEPATH += ../../src/


DEFINES += QT_MESSAGELOGCONTEXT

# Input
SOURCES += qltdebugexample.cpp ../../src/qltdebug.cpp
